// Platte lijst van alle Payload-veldnamen die themeFields() (zie
// themeFields.ts) definieert binnen een "theme"-groep. Gebruikt door
// ThemePresets.tsx om preset-waarden te lezen/schrijven zonder de hele
// tabs/row-structuur te hoeven doorlopen. Moet in sync blijven met
// themeFields.ts — als je daar een token toevoegt/hernoemt, doe het hier ook.
export const THEME_FIELD_NAMES = [
  // Typografie
  "fontSizeXs",
  "fontSizeSmall",
  "fontSizeStandard",
  "fontSizeMedium",
  "fontSizeLarge",
  "fontSizeXl",
  "fontSizeXxl",
  "fontFamilyPrimary",
  "fontFamilySecondary",
  "fontFamilyText",
  "fontFamilyAccent",
  "fontFamilyMono",
  "fontWeightLight",
  "fontWeightStandard",
  "fontWeightMedium",
  "fontWeightBold",
  "fontWeightHeavy",
  "lineHeightTight",
  "lineHeightStandard",
  "lineHeightRelaxed",
  "lineHeightLoose",
  "letterSpacingTight",
  "letterSpacingStandard",
  "letterSpacingWide",

  // Kleuren
  "colorPrimary",
  "colorSecondary",
  "colorAccent",
  "colorText",
  "colorBgPrimaryLight",
  "colorBgPrimaryMedium",
  "colorBgPrimaryDark",
  "colorBgSecondaryLight",
  "colorBgSecondaryMedium",
  "colorBgSecondaryDark",
  "colorWhite",
  "colorOffWhite",
  "colorLightGrey",
  "colorMediumGrey",
  "colorDarkGrey",
  "colorOffBlack",
  "colorBgBlack",
  "colorSuccess",
  "colorWarning",
  "colorError",

  // Vormgeving & Randen
  "borderRadiusNone",
  "borderRadiusSmall",
  "borderRadiusStandard",
  "borderRadiusMedium",
  "borderRadiusLarge",
  "borderRadiusFull",
  "borderWidthNone",
  "borderWidthThin",
  "borderWidthStandard",
  "borderWidthThick",
  "boxShadowNone",
  "boxShadowSmall",
  "boxShadowStandard",
  "boxShadowLarge",
  "boxShadowXl",

  // Ruimte & Afmetingen
  "spacingXs",
  "spacingSmall",
  "spacingStandard",
  "spacingMedium",
  "spacingLarge",
  "spacingXl",
  "spacingXxl",
  "maxWidthSmall",
  "maxWidthStandard",
  "maxWidthMedium",
  "maxWidthLarge",
  "maxWidthFull",

  // Media & Objecten
  "aspectRatioSquare",
  "aspectRatioVideo",
  "aspectRatioPhoto",
  "aspectRatioPortrait",

  // Interactie, Status & Lagen
  "transitionFast",
  "transitionStandard",
  "transitionSlow",
  "opacityLight",
  "opacityStandard",
  "opacityHeavy",
  "opacitySolid",
  "zIndexBase",
  "zIndexAbove",
  "zIndexDropdown",
  "zIndexOverlay",
  "zIndexModal",
] as const;
