/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    clients: Client;
    plugins: Plugin;
    'api-connections': ApiConnection;
    'site-templates': SiteTemplate;
    sites: Site;
    'site-plugins': SitePlugin;
    pages: Page;
    'time-entries': TimeEntry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    plugins: PluginsSelect<false> | PluginsSelect<true>;
    'api-connections': ApiConnectionsSelect<false> | ApiConnectionsSelect<true>;
    'site-templates': SiteTemplatesSelect<false> | SiteTemplatesSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    'site-plugins': SitePluginsSelect<false> | SitePluginsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'time-entries': TimeEntriesSelect<false> | TimeEntriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'client';
  /**
   * Voor een klant-gebruiker: de site waartoe deze gebruiker toegang heeft.
   */
  site?: (number | null) | Site;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  domain: string;
  client: number | Client;
  /**
   * Alleen gebruikt bij het aanmaken — kopieert het sjabloon eenmalig naar 'theme' hieronder.
   */
  startingTemplate?: (number | null) | SiteTemplate;
  theme?: {
    colors?: {
      primary?: string | null;
      secondary?: string | null;
      background?: string | null;
      text?: string | null;
    };
    fonts?: {
      heading?: string | null;
      body?: string | null;
    };
    borderRadius?: string | null;
    maxPageWidth?: string | null;
  };
  plan: 'budget' | 'premium';
  /**
   * stable = periodiek/beproefd, early = nieuwe bloktypes direct (zie doc §10).
   */
  updateChannel: 'stable' | 'early';
  /**
   * Voorbereiding op automatische facturatie: abonnementsprijs en -status van deze site.
   */
  billing?: {
    basePrice?: number | null;
    billingCycle?: ('monthly' | 'yearly') | null;
    billingStatus?: ('active' | 'paused' | 'cancelled') | null;
    subscriptionStartDate?: string | null;
  };
  vercel?: {
    projectId?: string | null;
    deployHookUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  status?: ('active' | 'inactive') | null;
  /**
   * Via welk merk/acquisitiekanaal deze klant binnenkwam.
   */
  brand: 'budget' | 'premium';
  /**
   * Voorbereiding op (deels) automatische facturatie, later eventueel gekoppeld aan Moneybird e.d.
   */
  billing?: {
    companyName?: string | null;
    kvkNumber?: string | null;
    vatNumber?: string | null;
    billingEmail?: string | null;
    address?: {
      street?: string | null;
      postalCode?: string | null;
      city?: string | null;
      country?: string | null;
    };
    /**
     * Bijv. het relatie-ID in Moneybird zodra die koppeling er is. Nu nog leeg/handmatig.
     */
    externalAccountingId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-templates".
 */
export interface SiteTemplate {
  id: number;
  name: string;
  thumbnail?: (number | null) | Media;
  theme?: {
    colors?: {
      primary?: string | null;
      secondary?: string | null;
      background?: string | null;
      text?: string | null;
    };
    fonts?: {
      heading?: string | null;
      body?: string | null;
    };
    borderRadius?: string | null;
    maxPageWidth?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  site: number | Site;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugins".
 */
export interface Plugin {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  status?: ('planned' | 'available') | null;
  /**
   * Standaardprijs per maand (EUR) voor deze plugin — basis voor toekomstige automatische facturatie. Per site te overschrijven via Site Plugins.
   */
  basePrice?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-connections".
 */
export interface ApiConnection {
  id: number;
  name: string;
  service: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-plugins".
 */
export interface SitePlugin {
  id: number;
  site: number | Site;
  plugin: number | Plugin;
  active?: boolean | null;
  /**
   * Leeg = gebruik de standaardprijs van de plugin. Alleen invullen bij een klantspecifieke afspraak.
   */
  priceOverride?: number | null;
  /**
   * Voor het bepalen van het eerste factuurmoment (proratie).
   */
  activatedAt?: string | null;
  settings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pagina's van ALLE sites staan hier samen (centrale database). Gebruik de 'site'-kolom of het filter om te scopen naar één klant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  site: number | Site;
  title: string;
  slug: string;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  /**
   * Alles hier is optioneel — leeg = erf van de site-instellingen.
   */
  themeOverrides?: {
    colors?: {
      primary?: string | null;
      secondary?: string | null;
      background?: string | null;
      text?: string | null;
    };
    fonts?: {
      heading?: string | null;
      body?: string | null;
    };
    borderRadius?: string | null;
    maxPageWidth?: string | null;
  };
  sections?:
    | {
        width?: ('full' | 'contained' | 'custom') | null;
        layout?: ('1-col' | '2-col-50-50' | '2-col-30-70') | null;
        background?: string | null;
        divider?: {
          type?: ('none' | 'wave' | 'diagonal' | 'curve') | null;
          color?: string | null;
        };
        blocks?:
          | (
              | {
                  variant?: ('centered' | 'centered-proof' | 'split' | 'video-bg' | 'full-bleed') | null;
                  heading: string;
                  subheading?: string | null;
                  image?: (number | null) | Media;
                  /**
                   * Bijv. 'Vertrouwd door 10.000+ klanten'. Leeg = niet tonen.
                   */
                  badge?: string | null;
                  cta?: {
                    label?: string | null;
                    href?: string | null;
                  };
                  /**
                   * Optionele rij met kengetallen onder de hero, bijv. '500+ Projecten'.
                   */
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'hero';
                }
              | {
                  imagePosition?: ('left' | 'right') | null;
                  image: number | Media;
                  heading?: string | null;
                  text?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'fotoTekst';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Tijdregistratie per kwartier. 'Doorbelasten' aanvinken voor werk dat bij de klant in rekening gebracht moet worden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-entries".
 */
export interface TimeEntry {
  id: number;
  client: number | Client;
  /**
   * Optioneel: leeg laten voor algemeen klantwerk dat niet aan één site hangt.
   */
  site?: (number | null) | Site;
  date: string;
  /**
   * In minuten, bij voorkeur afgerond op kwartieren (15/30/45/60).
   */
  minutes: number;
  description: string;
  /**
   * Uit = telt als eigen platformonderhoud, niet als klantwerk.
   */
  billable?: boolean | null;
  /**
   * Handmatig (of later automatisch) aan te vinken zodra dit is meegenomen in een factuur.
   */
  invoiced?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'plugins';
        value: number | Plugin;
      } | null)
    | ({
        relationTo: 'api-connections';
        value: number | ApiConnection;
      } | null)
    | ({
        relationTo: 'site-templates';
        value: number | SiteTemplate;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'site-plugins';
        value: number | SitePlugin;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'time-entries';
        value: number | TimeEntry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  site?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  status?: T;
  brand?: T;
  billing?:
    | T
    | {
        companyName?: T;
        kvkNumber?: T;
        vatNumber?: T;
        billingEmail?: T;
        address?:
          | T
          | {
              street?: T;
              postalCode?: T;
              city?: T;
              country?: T;
            };
        externalAccountingId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugins_select".
 */
export interface PluginsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  status?: T;
  basePrice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-connections_select".
 */
export interface ApiConnectionsSelect<T extends boolean = true> {
  name?: T;
  service?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-templates_select".
 */
export interface SiteTemplatesSelect<T extends boolean = true> {
  name?: T;
  thumbnail?: T;
  theme?:
    | T
    | {
        colors?:
          | T
          | {
              primary?: T;
              secondary?: T;
              background?: T;
              text?: T;
            };
        fonts?:
          | T
          | {
              heading?: T;
              body?: T;
            };
        borderRadius?: T;
        maxPageWidth?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  domain?: T;
  client?: T;
  startingTemplate?: T;
  theme?:
    | T
    | {
        colors?:
          | T
          | {
              primary?: T;
              secondary?: T;
              background?: T;
              text?: T;
            };
        fonts?:
          | T
          | {
              heading?: T;
              body?: T;
            };
        borderRadius?: T;
        maxPageWidth?: T;
      };
  plan?: T;
  updateChannel?: T;
  billing?:
    | T
    | {
        basePrice?: T;
        billingCycle?: T;
        billingStatus?: T;
        subscriptionStartDate?: T;
      };
  vercel?:
    | T
    | {
        projectId?: T;
        deployHookUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-plugins_select".
 */
export interface SitePluginsSelect<T extends boolean = true> {
  site?: T;
  plugin?: T;
  active?: T;
  priceOverride?: T;
  activatedAt?: T;
  settings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  themeOverrides?:
    | T
    | {
        colors?:
          | T
          | {
              primary?: T;
              secondary?: T;
              background?: T;
              text?: T;
            };
        fonts?:
          | T
          | {
              heading?: T;
              body?: T;
            };
        borderRadius?: T;
        maxPageWidth?: T;
      };
  sections?:
    | T
    | {
        width?: T;
        layout?: T;
        background?: T;
        divider?:
          | T
          | {
              type?: T;
              color?: T;
            };
        blocks?:
          | T
          | {
              hero?:
                | T
                | {
                    variant?: T;
                    heading?: T;
                    subheading?: T;
                    image?: T;
                    badge?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    stats?:
                      | T
                      | {
                          value?: T;
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              fotoTekst?:
                | T
                | {
                    imagePosition?: T;
                    image?: T;
                    heading?: T;
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-entries_select".
 */
export interface TimeEntriesSelect<T extends boolean = true> {
  client?: T;
  site?: T;
  date?: T;
  minutes?: T;
  description?: T;
  billable?: T;
  invoiced?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}