/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    clients: Client;
    plugins: Plugin;
    'api-connections': ApiConnection;
    'site-templates': SiteTemplate;
    sites: Site;
    'site-plugins': SitePlugin;
    pages: Page;
    'time-entries': TimeEntry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    plugins: PluginsSelect<false> | PluginsSelect<true>;
    'api-connections': ApiConnectionsSelect<false> | ApiConnectionsSelect<true>;
    'site-templates': SiteTemplatesSelect<false> | SiteTemplatesSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    'site-plugins': SitePluginsSelect<false> | SitePluginsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'time-entries': TimeEntriesSelect<false> | TimeEntriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'client';
  /**
   * Voor een klant-gebruiker: de site waartoe deze gebruiker toegang heeft.
   */
  site?: (number | null) | Site;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  domain: string;
  client: number | Client;
  /**
   * Alleen gebruikt bij het aanmaken — kopieert het sjabloon eenmalig naar 'theme' hieronder.
   */
  startingTemplate?: (number | null) | SiteTemplate;
  plan: 'budget' | 'premium';
  /**
   * stable = periodiek/beproefd, early = nieuwe bloktypes direct (zie doc §10).
   */
  updateChannel: 'stable' | 'early';
  theme?: {
    fontSizeXs?: string | null;
    fontSizeSmall?: string | null;
    /**
     * bv. 1rem
     */
    fontSizeStandard?: string | null;
    fontSizeMedium?: string | null;
    fontSizeLarge?: string | null;
    fontSizeXl?: string | null;
    fontSizeXxl?: string | null;
    /**
     * bv. Inter, sans-serif
     */
    fontFamilyPrimary?: string | null;
    fontFamilySecondary?: string | null;
    fontFamilyText?: string | null;
    fontFamilyAccent?: string | null;
    fontFamilyMono?: string | null;
    fontWeightLight?: string | null;
    fontWeightStandard?: string | null;
    fontWeightMedium?: string | null;
    fontWeightBold?: string | null;
    fontWeightHeavy?: string | null;
    lineHeightTight?: string | null;
    lineHeightStandard?: string | null;
    lineHeightRelaxed?: string | null;
    lineHeightLoose?: string | null;
    letterSpacingTight?: string | null;
    letterSpacingStandard?: string | null;
    letterSpacingWide?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorPrimary?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorSecondary?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorAccent?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorText?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgPrimaryLight?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgPrimaryMedium?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgPrimaryDark?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgSecondaryLight?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgSecondaryMedium?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgSecondaryDark?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorWhite?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorOffWhite?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorLightGrey?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorMediumGrey?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorDarkGrey?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorOffBlack?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgBlack?: string | null;
    /**
     * Hex-waarde. Status-kleuren: nodig voor formulier-validaties en notificaties.
     */
    colorSuccess?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorWarning?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorError?: string | null;
    borderRadiusNone?: string | null;
    borderRadiusSmall?: string | null;
    borderRadiusStandard?: string | null;
    borderRadiusMedium?: string | null;
    borderRadiusLarge?: string | null;
    borderRadiusFull?: string | null;
    borderWidthNone?: string | null;
    borderWidthThin?: string | null;
    borderWidthStandard?: string | null;
    borderWidthThick?: string | null;
    boxShadowNone?: string | null;
    /**
     * bv. 0 1px 2px rgba(0,0,0,.1)
     */
    boxShadowSmall?: string | null;
    boxShadowStandard?: string | null;
    boxShadowLarge?: string | null;
    boxShadowXl?: string | null;
    spacingXs?: string | null;
    spacingSmall?: string | null;
    spacingStandard?: string | null;
    spacingMedium?: string | null;
    spacingLarge?: string | null;
    spacingXl?: string | null;
    spacingXxl?: string | null;
    maxWidthSmall?: string | null;
    maxWidthStandard?: string | null;
    maxWidthMedium?: string | null;
    maxWidthLarge?: string | null;
    maxWidthFull?: string | null;
    /**
     * 1:1 — dwingt geüploade afbeeldingen via object-fit: cover in een vast grid.
     */
    aspectRatioSquare?: string | null;
    /**
     * 16:9
     */
    aspectRatioVideo?: string | null;
    /**
     * 4:3
     */
    aspectRatioPhoto?: string | null;
    /**
     * 3:4
     */
    aspectRatioPortrait?: string | null;
    /**
     * bv. 100ms ease
     */
    transitionFast?: string | null;
    transitionStandard?: string | null;
    transitionSlow?: string | null;
    opacityLight?: number | null;
    opacityStandard?: number | null;
    opacityHeavy?: number | null;
    opacitySolid?: number | null;
    zIndexBase?: number | null;
    zIndexAbove?: number | null;
    zIndexDropdown?: number | null;
    zIndexOverlay?: number | null;
    zIndexModal?: number | null;
  };
  /**
   * Voorbereiding op automatische facturatie: abonnementsprijs en -status van deze site.
   */
  billing?: {
    basePrice?: number | null;
    billingCycle?: ('monthly' | 'yearly') | null;
    billingStatus?: ('active' | 'paused' | 'cancelled') | null;
    subscriptionStartDate?: string | null;
  };
  vercel?: {
    projectId?: string | null;
    deployHookUrl?: string | null;
  };
  settings?: {
    general?: {
      siteName?: string | null;
      favicon?: (number | null) | Media;
      locale?: ('nl' | 'en') | null;
    };
    seo?: {
      /**
       * Gebruikt wanneer een pagina geen eigen meta title heeft.
       */
      metaTitle?: string | null;
      /**
       * Gebruikt wanneer een pagina geen eigen meta description heeft.
       */
      metaDescription?: string | null;
      ogImage?: (number | null) | Media;
    };
    analytics?: {
      /**
       * Bijv. G-XXXXXXXXXX.
       */
      gaId?: string | null;
      /**
       * Ruwe HTML/script-tags, bijv. voor Google Tag Manager of andere tracking.
       */
      headScripts?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  status?: ('active' | 'inactive') | null;
  /**
   * Via welk merk/acquisitiekanaal deze klant binnenkwam.
   */
  brand: 'budget' | 'premium';
  /**
   * Voorbereiding op (deels) automatische facturatie, later eventueel gekoppeld aan Moneybird e.d.
   */
  billing?: {
    companyName?: string | null;
    kvkNumber?: string | null;
    vatNumber?: string | null;
    billingEmail?: string | null;
    address?: {
      street?: string | null;
      postalCode?: string | null;
      city?: string | null;
      country?: string | null;
    };
    /**
     * Bijv. het relatie-ID in Moneybird zodra die koppeling er is. Nu nog leeg/handmatig.
     */
    externalAccountingId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-templates".
 */
export interface SiteTemplate {
  id: number;
  name: string;
  thumbnail?: (number | null) | Media;
  theme?: {
    fontSizeXs?: string | null;
    fontSizeSmall?: string | null;
    /**
     * bv. 1rem
     */
    fontSizeStandard?: string | null;
    fontSizeMedium?: string | null;
    fontSizeLarge?: string | null;
    fontSizeXl?: string | null;
    fontSizeXxl?: string | null;
    /**
     * bv. Inter, sans-serif
     */
    fontFamilyPrimary?: string | null;
    fontFamilySecondary?: string | null;
    fontFamilyText?: string | null;
    fontFamilyAccent?: string | null;
    fontFamilyMono?: string | null;
    fontWeightLight?: string | null;
    fontWeightStandard?: string | null;
    fontWeightMedium?: string | null;
    fontWeightBold?: string | null;
    fontWeightHeavy?: string | null;
    lineHeightTight?: string | null;
    lineHeightStandard?: string | null;
    lineHeightRelaxed?: string | null;
    lineHeightLoose?: string | null;
    letterSpacingTight?: string | null;
    letterSpacingStandard?: string | null;
    letterSpacingWide?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorPrimary?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorSecondary?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorAccent?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorText?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgPrimaryLight?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgPrimaryMedium?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgPrimaryDark?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgSecondaryLight?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgSecondaryMedium?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgSecondaryDark?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorWhite?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorOffWhite?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorLightGrey?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorMediumGrey?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorDarkGrey?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorOffBlack?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgBlack?: string | null;
    /**
     * Hex-waarde. Status-kleuren: nodig voor formulier-validaties en notificaties.
     */
    colorSuccess?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorWarning?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorError?: string | null;
    borderRadiusNone?: string | null;
    borderRadiusSmall?: string | null;
    borderRadiusStandard?: string | null;
    borderRadiusMedium?: string | null;
    borderRadiusLarge?: string | null;
    borderRadiusFull?: string | null;
    borderWidthNone?: string | null;
    borderWidthThin?: string | null;
    borderWidthStandard?: string | null;
    borderWidthThick?: string | null;
    boxShadowNone?: string | null;
    /**
     * bv. 0 1px 2px rgba(0,0,0,.1)
     */
    boxShadowSmall?: string | null;
    boxShadowStandard?: string | null;
    boxShadowLarge?: string | null;
    boxShadowXl?: string | null;
    spacingXs?: string | null;
    spacingSmall?: string | null;
    spacingStandard?: string | null;
    spacingMedium?: string | null;
    spacingLarge?: string | null;
    spacingXl?: string | null;
    spacingXxl?: string | null;
    maxWidthSmall?: string | null;
    maxWidthStandard?: string | null;
    maxWidthMedium?: string | null;
    maxWidthLarge?: string | null;
    maxWidthFull?: string | null;
    /**
     * 1:1 — dwingt geüploade afbeeldingen via object-fit: cover in een vast grid.
     */
    aspectRatioSquare?: string | null;
    /**
     * 16:9
     */
    aspectRatioVideo?: string | null;
    /**
     * 4:3
     */
    aspectRatioPhoto?: string | null;
    /**
     * 3:4
     */
    aspectRatioPortrait?: string | null;
    /**
     * bv. 100ms ease
     */
    transitionFast?: string | null;
    transitionStandard?: string | null;
    transitionSlow?: string | null;
    opacityLight?: number | null;
    opacityStandard?: number | null;
    opacityHeavy?: number | null;
    opacitySolid?: number | null;
    zIndexBase?: number | null;
    zIndexAbove?: number | null;
    zIndexDropdown?: number | null;
    zIndexOverlay?: number | null;
    zIndexModal?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  site: number | Site;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugins".
 */
export interface Plugin {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  status?: ('planned' | 'available') | null;
  /**
   * Standaardprijs per maand (EUR) voor deze plugin — basis voor toekomstige automatische facturatie. Per site te overschrijven via Site Plugins.
   */
  basePrice?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-connections".
 */
export interface ApiConnection {
  id: number;
  name: string;
  service: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-plugins".
 */
export interface SitePlugin {
  id: number;
  site: number | Site;
  plugin: number | Plugin;
  active?: boolean | null;
  /**
   * Leeg = gebruik de standaardprijs van de plugin. Alleen invullen bij een klantspecifieke afspraak.
   */
  priceOverride?: number | null;
  /**
   * Voor het bepalen van het eerste factuurmoment (proratie).
   */
  activatedAt?: string | null;
  settings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pagina's van ALLE sites staan hier samen (centrale database). Gebruik de 'site'-kolom of het filter om te scopen naar één klant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  site: number | Site;
  title: string;
  slug: string;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  /**
   * Alles hier is optioneel — leeg = erf van de site-instellingen.
   */
  themeOverrides?: {
    fontSizeXs?: string | null;
    fontSizeSmall?: string | null;
    /**
     * bv. 1rem
     */
    fontSizeStandard?: string | null;
    fontSizeMedium?: string | null;
    fontSizeLarge?: string | null;
    fontSizeXl?: string | null;
    fontSizeXxl?: string | null;
    /**
     * bv. Inter, sans-serif
     */
    fontFamilyPrimary?: string | null;
    fontFamilySecondary?: string | null;
    fontFamilyText?: string | null;
    fontFamilyAccent?: string | null;
    fontFamilyMono?: string | null;
    fontWeightLight?: string | null;
    fontWeightStandard?: string | null;
    fontWeightMedium?: string | null;
    fontWeightBold?: string | null;
    fontWeightHeavy?: string | null;
    lineHeightTight?: string | null;
    lineHeightStandard?: string | null;
    lineHeightRelaxed?: string | null;
    lineHeightLoose?: string | null;
    letterSpacingTight?: string | null;
    letterSpacingStandard?: string | null;
    letterSpacingWide?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorPrimary?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorSecondary?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorAccent?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorText?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgPrimaryLight?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgPrimaryMedium?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgPrimaryDark?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgSecondaryLight?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgSecondaryMedium?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgSecondaryDark?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorWhite?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorOffWhite?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorLightGrey?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorMediumGrey?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorDarkGrey?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorOffBlack?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorBgBlack?: string | null;
    /**
     * Hex-waarde. Status-kleuren: nodig voor formulier-validaties en notificaties.
     */
    colorSuccess?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorWarning?: string | null;
    /**
     * Hex-waarde, bv. #4338ca
     */
    colorError?: string | null;
    borderRadiusNone?: string | null;
    borderRadiusSmall?: string | null;
    borderRadiusStandard?: string | null;
    borderRadiusMedium?: string | null;
    borderRadiusLarge?: string | null;
    borderRadiusFull?: string | null;
    borderWidthNone?: string | null;
    borderWidthThin?: string | null;
    borderWidthStandard?: string | null;
    borderWidthThick?: string | null;
    boxShadowNone?: string | null;
    /**
     * bv. 0 1px 2px rgba(0,0,0,.1)
     */
    boxShadowSmall?: string | null;
    boxShadowStandard?: string | null;
    boxShadowLarge?: string | null;
    boxShadowXl?: string | null;
    spacingXs?: string | null;
    spacingSmall?: string | null;
    spacingStandard?: string | null;
    spacingMedium?: string | null;
    spacingLarge?: string | null;
    spacingXl?: string | null;
    spacingXxl?: string | null;
    maxWidthSmall?: string | null;
    maxWidthStandard?: string | null;
    maxWidthMedium?: string | null;
    maxWidthLarge?: string | null;
    maxWidthFull?: string | null;
    /**
     * 1:1 — dwingt geüploade afbeeldingen via object-fit: cover in een vast grid.
     */
    aspectRatioSquare?: string | null;
    /**
     * 16:9
     */
    aspectRatioVideo?: string | null;
    /**
     * 4:3
     */
    aspectRatioPhoto?: string | null;
    /**
     * 3:4
     */
    aspectRatioPortrait?: string | null;
    /**
     * bv. 100ms ease
     */
    transitionFast?: string | null;
    transitionStandard?: string | null;
    transitionSlow?: string | null;
    opacityLight?: number | null;
    opacityStandard?: number | null;
    opacityHeavy?: number | null;
    opacitySolid?: number | null;
    zIndexBase?: number | null;
    zIndexAbove?: number | null;
    zIndexDropdown?: number | null;
    zIndexOverlay?: number | null;
    zIndexModal?: number | null;
  };
  sections?:
    | {
        width?: ('full' | 'contained' | 'custom') | null;
        layout?: ('1-col' | '2-col-50-50' | '2-col-30-70') | null;
        background?: string | null;
        divider?: {
          type?: ('none' | 'wave' | 'diagonal' | 'curve') | null;
          color?: string | null;
        };
        blocks?:
          | (
              | {
                  variant?: ('centered' | 'centered-proof' | 'split' | 'video-bg' | 'full-bleed') | null;
                  heading: string;
                  subheading?: string | null;
                  image?: (number | null) | Media;
                  /**
                   * Bijv. 'Vertrouwd door 10.000+ klanten'. Leeg = niet tonen.
                   */
                  badge?: string | null;
                  cta?: {
                    label?: string | null;
                    href?: string | null;
                  };
                  /**
                   * Optionele rij met kengetallen onder de hero, bijv. '500+ Projecten'.
                   */
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'hero';
                }
              | {
                  imagePosition?: ('left' | 'right') | null;
                  image: number | Media;
                  heading?: string | null;
                  text?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'fotoTekst';
                }
              | {
                  align?: ('left' | 'center') | null;
                  /**
                   * Bijv. 'DIENSTEN' of 'WAAROM WIJ'. Optioneel.
                   */
                  eyebrow?: string | null;
                  heading: string;
                  subheading?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'sectionHeading';
                }
              | {
                  columns?: ('2' | '3' | '4') | null;
                  items?:
                    | {
                        /**
                         * Emoji of korte tekst als icoon, bijv. '⚡' of '24/7'.
                         */
                        icon?: string | null;
                        heading: string;
                        text?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'uspGrid';
                }
              | {
                  items?:
                    | {
                        /**
                         * Bijv. '500+' of '98%'.
                         */
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'stats';
                }
              | {
                  style?: ('solid' | 'soft') | null;
                  heading: string;
                  text?: string | null;
                  cta: {
                    label: string;
                    href: string;
                  };
                  secondaryCta?: {
                    label?: string | null;
                    href?: string | null;
                  };
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'ctaBanner';
                }
              | {
                  layout?: ('grid' | 'single') | null;
                  items?:
                    | {
                        quote: string;
                        name: string;
                        role?: string | null;
                        avatar?: (number | null) | Media;
                        /**
                         * 1 t/m 5 sterren. Leeg = geen sterren tonen.
                         */
                        rating?: number | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'testimonials';
                }
              | {
                  /**
                   * Bijv. 'Vertrouwd door'. Optioneel.
                   */
                  heading?: string | null;
                  logos?:
                    | {
                        image: number | Media;
                        /**
                         * Bedrijfsnaam, voor alt-tekst.
                         */
                        name?: string | null;
                        /**
                         * Optionele link naar de klant/partner.
                         */
                        href?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'logoBar';
                }
              | {
                  variant?: ('formInfo' | 'split' | 'locations') | null;
                  /**
                   * Bijv. 'NEEM CONTACT OP'. Optioneel.
                   */
                  eyebrow?: string | null;
                  heading: string;
                  subheading?: string | null;
                  image?: (number | null) | Media;
                  submitLabel?: string | null;
                  /**
                   * Optioneel — endpoint waar het formulier naartoe post (bijv. Formspree-URL). Leeg = niet-functioneel voorbeeld.
                   */
                  formAction?: string | null;
                  contactInfo?:
                    | {
                        /**
                         * Emoji of korte tekst, bijv. '📍' of '☎'.
                         */
                        icon?: string | null;
                        /**
                         * Bijv. 'Adres', 'Telefoon', 'E-mail'.
                         */
                        label: string;
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  locations?:
                    | {
                        name: string;
                        phone?: string | null;
                        email?: string | null;
                        address?: string | null;
                        cta?: {
                          label?: string | null;
                          href?: string | null;
                        };
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'contact';
                }
              | {
                  variant?: ('image' | 'icon' | 'numbered') | null;
                  eyebrow?: string | null;
                  heading: string;
                  subheading?: string | null;
                  cta?: {
                    label?: string | null;
                    href?: string | null;
                  };
                  steps?:
                    | {
                        /**
                         * Gebruikt bij variant 'Afbeelding + nummerbadge'.
                         */
                        image?: (number | null) | Media;
                        /**
                         * Emoji of korte tekst als icoon.
                         */
                        icon?: string | null;
                        title: string;
                        text?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'stepBox';
                }
              | {
                  variant?: ('cards' | 'photo') | null;
                  eyebrow?: string | null;
                  heading: string;
                  subheading?: string | null;
                  cta?: {
                    label?: string | null;
                    href?: string | null;
                  };
                  columns?: ('2' | '3' | '4') | null;
                  members?:
                    | {
                        photo?: (number | null) | Media;
                        name: string;
                        role?: string | null;
                        /**
                         * Alleen gebruikt bij variant 'Kaarten'.
                         */
                        bio?: string | null;
                        /**
                         * Alleen gebruikt bij variant 'Kaarten'.
                         */
                        email?: string | null;
                        /**
                         * Alleen gebruikt bij variant 'Kaarten'. Bijv. 'Meer info'.
                         */
                        ctaLabel?: string | null;
                        /**
                         * Alleen gebruikt bij variant 'Portretfoto's'.
                         */
                        socials?:
                          | {
                              /**
                               * Bijv. 'Twitter' of '𝕏'.
                               */
                              label: string;
                              href: string;
                              id?: string | null;
                            }[]
                          | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'teamGrid';
                }
              | {
                  eyebrow?: string | null;
                  heading: string;
                  subheading?: string | null;
                  tiers?:
                    | {
                        name: string;
                        /**
                         * Bijv. '€29' of 'Op aanvraag'.
                         */
                        price: string;
                        /**
                         * Bijv. 'per maand'. Optioneel.
                         */
                        period?: string | null;
                        description?: string | null;
                        features?:
                          | {
                              text: string;
                              id?: string | null;
                            }[]
                          | null;
                        cta?: {
                          label?: string | null;
                          href?: string | null;
                        };
                        featured?: boolean | null;
                        /**
                         * Bijv. 'Meest gekozen'. Alleen zichtbaar als 'Uitgelicht' aanstaat.
                         */
                        badge?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'pricingTable';
                }
              | {
                  eyebrow?: string | null;
                  heading?: string | null;
                  subheading?: string | null;
                  columns?: ('2' | '3' | '4') | null;
                  images?:
                    | {
                        image: number | Media;
                        caption?: string | null;
                        span?: ('normal' | 'wide' | 'tall') | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'gallery';
                }
              | {
                  variant?: ('centered' | 'split') | null;
                  eyebrow?: string | null;
                  heading: string;
                  subheading?: string | null;
                  image?: (number | null) | Media;
                  items?:
                    | {
                        question: string;
                        answer: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'faq';
                }
              | {
                  variant?: ('detailed' | 'simple') | null;
                  eyebrow?: string | null;
                  heading: string;
                  items?:
                    | {
                        /**
                         * Klein label links. Alleen bij 'Uitgebreid'.
                         */
                        tag?: string | null;
                        title: string;
                        /**
                         * Alleen bij 'Uitgebreid'.
                         */
                        text?: string | null;
                        /**
                         * Optioneel — toont een pijl als dit is ingevuld.
                         */
                        href?: string | null;
                        /**
                         * Alleen bij 'Simpel'.
                         */
                        tags?:
                          | {
                              text: string;
                              id?: string | null;
                            }[]
                          | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'list';
                }
              | {
                  eyebrow?: string | null;
                  heading?: string | null;
                  columns?: ('1' | '2') | null;
                  body: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'richText';
                }
              | {
                  eyebrow?: string | null;
                  heading?: string | null;
                  subheading?: string | null;
                  poster: number | Media;
                  /**
                   * Voor directe afspelen op de pagina. Leeg laten als je 'Externe video-link' gebruikt.
                   */
                  videoFile?: (number | null) | Media;
                  /**
                   * YouTube/Vimeo-URL — de play-knop linkt hiernaartoe als er geen video-bestand is.
                   */
                  videoUrl?: string | null;
                  features?:
                    | {
                        /**
                         * Emoji of korte tekst.
                         */
                        icon?: string | null;
                        title: string;
                        text?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'video';
                }
              | {
                  variant?: ('centered' | 'split') | null;
                  eyebrow?: string | null;
                  heading: string;
                  subheading?: string | null;
                  image?: (number | null) | Media;
                  showNameField?: boolean | null;
                  submitLabel?: string | null;
                  /**
                   * Optioneel — endpoint waar het formulier naartoe post.
                   */
                  formAction?: string | null;
                  /**
                   * Kleine tekst onder het formulier, bijv. privacy-mededeling.
                   */
                  disclaimer?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'emailOptin';
                }
              | {
                  eyebrow?: string | null;
                  heading: string;
                  subheading?: string | null;
                  columns?: ('1' | '2') | null;
                  items?:
                    | {
                        image?: (number | null) | Media;
                        name: string;
                        description?: string | null;
                        /**
                         * Bijv. '€20' of 'Op aanvraag'.
                         */
                        price: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'priceList';
                }
              | {
                  variant?: ('horizontal' | 'vertical') | null;
                  eyebrow?: string | null;
                  heading: string;
                  subheading?: string | null;
                  items?:
                    | {
                        /**
                         * Bijv. '2024' of 'Q1 2025'.
                         */
                        date: string;
                        /**
                         * Emoji, alleen bij Verticaal.
                         */
                        icon?: string | null;
                        title: string;
                        text?: string | null;
                        cta?: {
                          label?: string | null;
                          href?: string | null;
                        };
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'timeline';
                }
              | {
                  variant?: ('bar' | 'iconsRound') | null;
                  heading?: string | null;
                  text?: string | null;
                  links?:
                    | {
                        /**
                         * Bijv. 'Instagram' of '📷'.
                         */
                        label: string;
                        href: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'social';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Tijdregistratie per kwartier. 'Doorbelasten' aanvinken voor werk dat bij de klant in rekening gebracht moet worden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-entries".
 */
export interface TimeEntry {
  id: number;
  client: number | Client;
  /**
   * Optioneel: leeg laten voor algemeen klantwerk dat niet aan één site hangt.
   */
  site?: (number | null) | Site;
  date: string;
  /**
   * In minuten, bij voorkeur afgerond op kwartieren (15/30/45/60).
   */
  minutes: number;
  description: string;
  /**
   * Uit = telt als eigen platformonderhoud, niet als klantwerk.
   */
  billable?: boolean | null;
  /**
   * Handmatig (of later automatisch) aan te vinken zodra dit is meegenomen in een factuur.
   */
  invoiced?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'plugins';
        value: number | Plugin;
      } | null)
    | ({
        relationTo: 'api-connections';
        value: number | ApiConnection;
      } | null)
    | ({
        relationTo: 'site-templates';
        value: number | SiteTemplate;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'site-plugins';
        value: number | SitePlugin;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'time-entries';
        value: number | TimeEntry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  site?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  status?: T;
  brand?: T;
  billing?:
    | T
    | {
        companyName?: T;
        kvkNumber?: T;
        vatNumber?: T;
        billingEmail?: T;
        address?:
          | T
          | {
              street?: T;
              postalCode?: T;
              city?: T;
              country?: T;
            };
        externalAccountingId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugins_select".
 */
export interface PluginsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  status?: T;
  basePrice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-connections_select".
 */
export interface ApiConnectionsSelect<T extends boolean = true> {
  name?: T;
  service?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-templates_select".
 */
export interface SiteTemplatesSelect<T extends boolean = true> {
  name?: T;
  thumbnail?: T;
  theme?:
    | T
    | {
        fontSizeXs?: T;
        fontSizeSmall?: T;
        fontSizeStandard?: T;
        fontSizeMedium?: T;
        fontSizeLarge?: T;
        fontSizeXl?: T;
        fontSizeXxl?: T;
        fontFamilyPrimary?: T;
        fontFamilySecondary?: T;
        fontFamilyText?: T;
        fontFamilyAccent?: T;
        fontFamilyMono?: T;
        fontWeightLight?: T;
        fontWeightStandard?: T;
        fontWeightMedium?: T;
        fontWeightBold?: T;
        fontWeightHeavy?: T;
        lineHeightTight?: T;
        lineHeightStandard?: T;
        lineHeightRelaxed?: T;
        lineHeightLoose?: T;
        letterSpacingTight?: T;
        letterSpacingStandard?: T;
        letterSpacingWide?: T;
        colorPrimary?: T;
        colorSecondary?: T;
        colorAccent?: T;
        colorText?: T;
        colorBgPrimaryLight?: T;
        colorBgPrimaryMedium?: T;
        colorBgPrimaryDark?: T;
        colorBgSecondaryLight?: T;
        colorBgSecondaryMedium?: T;
        colorBgSecondaryDark?: T;
        colorWhite?: T;
        colorOffWhite?: T;
        colorLightGrey?: T;
        colorMediumGrey?: T;
        colorDarkGrey?: T;
        colorOffBlack?: T;
        colorBgBlack?: T;
        colorSuccess?: T;
        colorWarning?: T;
        colorError?: T;
        borderRadiusNone?: T;
        borderRadiusSmall?: T;
        borderRadiusStandard?: T;
        borderRadiusMedium?: T;
        borderRadiusLarge?: T;
        borderRadiusFull?: T;
        borderWidthNone?: T;
        borderWidthThin?: T;
        borderWidthStandard?: T;
        borderWidthThick?: T;
        boxShadowNone?: T;
        boxShadowSmall?: T;
        boxShadowStandard?: T;
        boxShadowLarge?: T;
        boxShadowXl?: T;
        spacingXs?: T;
        spacingSmall?: T;
        spacingStandard?: T;
        spacingMedium?: T;
        spacingLarge?: T;
        spacingXl?: T;
        spacingXxl?: T;
        maxWidthSmall?: T;
        maxWidthStandard?: T;
        maxWidthMedium?: T;
        maxWidthLarge?: T;
        maxWidthFull?: T;
        aspectRatioSquare?: T;
        aspectRatioVideo?: T;
        aspectRatioPhoto?: T;
        aspectRatioPortrait?: T;
        transitionFast?: T;
        transitionStandard?: T;
        transitionSlow?: T;
        opacityLight?: T;
        opacityStandard?: T;
        opacityHeavy?: T;
        opacitySolid?: T;
        zIndexBase?: T;
        zIndexAbove?: T;
        zIndexDropdown?: T;
        zIndexOverlay?: T;
        zIndexModal?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  domain?: T;
  client?: T;
  startingTemplate?: T;
  plan?: T;
  updateChannel?: T;
  theme?:
    | T
    | {
        fontSizeXs?: T;
        fontSizeSmall?: T;
        fontSizeStandard?: T;
        fontSizeMedium?: T;
        fontSizeLarge?: T;
        fontSizeXl?: T;
        fontSizeXxl?: T;
        fontFamilyPrimary?: T;
        fontFamilySecondary?: T;
        fontFamilyText?: T;
        fontFamilyAccent?: T;
        fontFamilyMono?: T;
        fontWeightLight?: T;
        fontWeightStandard?: T;
        fontWeightMedium?: T;
        fontWeightBold?: T;
        fontWeightHeavy?: T;
        lineHeightTight?: T;
        lineHeightStandard?: T;
        lineHeightRelaxed?: T;
        lineHeightLoose?: T;
        letterSpacingTight?: T;
        letterSpacingStandard?: T;
        letterSpacingWide?: T;
        colorPrimary?: T;
        colorSecondary?: T;
        colorAccent?: T;
        colorText?: T;
        colorBgPrimaryLight?: T;
        colorBgPrimaryMedium?: T;
        colorBgPrimaryDark?: T;
        colorBgSecondaryLight?: T;
        colorBgSecondaryMedium?: T;
        colorBgSecondaryDark?: T;
        colorWhite?: T;
        colorOffWhite?: T;
        colorLightGrey?: T;
        colorMediumGrey?: T;
        colorDarkGrey?: T;
        colorOffBlack?: T;
        colorBgBlack?: T;
        colorSuccess?: T;
        colorWarning?: T;
        colorError?: T;
        borderRadiusNone?: T;
        borderRadiusSmall?: T;
        borderRadiusStandard?: T;
        borderRadiusMedium?: T;
        borderRadiusLarge?: T;
        borderRadiusFull?: T;
        borderWidthNone?: T;
        borderWidthThin?: T;
        borderWidthStandard?: T;
        borderWidthThick?: T;
        boxShadowNone?: T;
        boxShadowSmall?: T;
        boxShadowStandard?: T;
        boxShadowLarge?: T;
        boxShadowXl?: T;
        spacingXs?: T;
        spacingSmall?: T;
        spacingStandard?: T;
        spacingMedium?: T;
        spacingLarge?: T;
        spacingXl?: T;
        spacingXxl?: T;
        maxWidthSmall?: T;
        maxWidthStandard?: T;
        maxWidthMedium?: T;
        maxWidthLarge?: T;
        maxWidthFull?: T;
        aspectRatioSquare?: T;
        aspectRatioVideo?: T;
        aspectRatioPhoto?: T;
        aspectRatioPortrait?: T;
        transitionFast?: T;
        transitionStandard?: T;
        transitionSlow?: T;
        opacityLight?: T;
        opacityStandard?: T;
        opacityHeavy?: T;
        opacitySolid?: T;
        zIndexBase?: T;
        zIndexAbove?: T;
        zIndexDropdown?: T;
        zIndexOverlay?: T;
        zIndexModal?: T;
      };
  billing?:
    | T
    | {
        basePrice?: T;
        billingCycle?: T;
        billingStatus?: T;
        subscriptionStartDate?: T;
      };
  vercel?:
    | T
    | {
        projectId?: T;
        deployHookUrl?: T;
      };
  settings?:
    | T
    | {
        general?:
          | T
          | {
              siteName?: T;
              favicon?: T;
              locale?: T;
            };
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              ogImage?: T;
            };
        analytics?:
          | T
          | {
              gaId?: T;
              headScripts?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-plugins_select".
 */
export interface SitePluginsSelect<T extends boolean = true> {
  site?: T;
  plugin?: T;
  active?: T;
  priceOverride?: T;
  activatedAt?: T;
  settings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  themeOverrides?:
    | T
    | {
        fontSizeXs?: T;
        fontSizeSmall?: T;
        fontSizeStandard?: T;
        fontSizeMedium?: T;
        fontSizeLarge?: T;
        fontSizeXl?: T;
        fontSizeXxl?: T;
        fontFamilyPrimary?: T;
        fontFamilySecondary?: T;
        fontFamilyText?: T;
        fontFamilyAccent?: T;
        fontFamilyMono?: T;
        fontWeightLight?: T;
        fontWeightStandard?: T;
        fontWeightMedium?: T;
        fontWeightBold?: T;
        fontWeightHeavy?: T;
        lineHeightTight?: T;
        lineHeightStandard?: T;
        lineHeightRelaxed?: T;
        lineHeightLoose?: T;
        letterSpacingTight?: T;
        letterSpacingStandard?: T;
        letterSpacingWide?: T;
        colorPrimary?: T;
        colorSecondary?: T;
        colorAccent?: T;
        colorText?: T;
        colorBgPrimaryLight?: T;
        colorBgPrimaryMedium?: T;
        colorBgPrimaryDark?: T;
        colorBgSecondaryLight?: T;
        colorBgSecondaryMedium?: T;
        colorBgSecondaryDark?: T;
        colorWhite?: T;
        colorOffWhite?: T;
        colorLightGrey?: T;
        colorMediumGrey?: T;
        colorDarkGrey?: T;
        colorOffBlack?: T;
        colorBgBlack?: T;
        colorSuccess?: T;
        colorWarning?: T;
        colorError?: T;
        borderRadiusNone?: T;
        borderRadiusSmall?: T;
        borderRadiusStandard?: T;
        borderRadiusMedium?: T;
        borderRadiusLarge?: T;
        borderRadiusFull?: T;
        borderWidthNone?: T;
        borderWidthThin?: T;
        borderWidthStandard?: T;
        borderWidthThick?: T;
        boxShadowNone?: T;
        boxShadowSmall?: T;
        boxShadowStandard?: T;
        boxShadowLarge?: T;
        boxShadowXl?: T;
        spacingXs?: T;
        spacingSmall?: T;
        spacingStandard?: T;
        spacingMedium?: T;
        spacingLarge?: T;
        spacingXl?: T;
        spacingXxl?: T;
        maxWidthSmall?: T;
        maxWidthStandard?: T;
        maxWidthMedium?: T;
        maxWidthLarge?: T;
        maxWidthFull?: T;
        aspectRatioSquare?: T;
        aspectRatioVideo?: T;
        aspectRatioPhoto?: T;
        aspectRatioPortrait?: T;
        transitionFast?: T;
        transitionStandard?: T;
        transitionSlow?: T;
        opacityLight?: T;
        opacityStandard?: T;
        opacityHeavy?: T;
        opacitySolid?: T;
        zIndexBase?: T;
        zIndexAbove?: T;
        zIndexDropdown?: T;
        zIndexOverlay?: T;
        zIndexModal?: T;
      };
  sections?:
    | T
    | {
        width?: T;
        layout?: T;
        background?: T;
        divider?:
          | T
          | {
              type?: T;
              color?: T;
            };
        blocks?:
          | T
          | {
              hero?:
                | T
                | {
                    variant?: T;
                    heading?: T;
                    subheading?: T;
                    image?: T;
                    badge?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    stats?:
                      | T
                      | {
                          value?: T;
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              fotoTekst?:
                | T
                | {
                    imagePosition?: T;
                    image?: T;
                    heading?: T;
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
              sectionHeading?:
                | T
                | {
                    align?: T;
                    eyebrow?: T;
                    heading?: T;
                    subheading?: T;
                    id?: T;
                    blockName?: T;
                  };
              uspGrid?:
                | T
                | {
                    columns?: T;
                    items?:
                      | T
                      | {
                          icon?: T;
                          heading?: T;
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              stats?:
                | T
                | {
                    items?:
                      | T
                      | {
                          value?: T;
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              ctaBanner?:
                | T
                | {
                    style?: T;
                    heading?: T;
                    text?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    secondaryCta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              testimonials?:
                | T
                | {
                    layout?: T;
                    items?:
                      | T
                      | {
                          quote?: T;
                          name?: T;
                          role?: T;
                          avatar?: T;
                          rating?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              logoBar?:
                | T
                | {
                    heading?: T;
                    logos?:
                      | T
                      | {
                          image?: T;
                          name?: T;
                          href?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              contact?:
                | T
                | {
                    variant?: T;
                    eyebrow?: T;
                    heading?: T;
                    subheading?: T;
                    image?: T;
                    submitLabel?: T;
                    formAction?: T;
                    contactInfo?:
                      | T
                      | {
                          icon?: T;
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    locations?:
                      | T
                      | {
                          name?: T;
                          phone?: T;
                          email?: T;
                          address?: T;
                          cta?:
                            | T
                            | {
                                label?: T;
                                href?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              stepBox?:
                | T
                | {
                    variant?: T;
                    eyebrow?: T;
                    heading?: T;
                    subheading?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    steps?:
                      | T
                      | {
                          image?: T;
                          icon?: T;
                          title?: T;
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              teamGrid?:
                | T
                | {
                    variant?: T;
                    eyebrow?: T;
                    heading?: T;
                    subheading?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    columns?: T;
                    members?:
                      | T
                      | {
                          photo?: T;
                          name?: T;
                          role?: T;
                          bio?: T;
                          email?: T;
                          ctaLabel?: T;
                          socials?:
                            | T
                            | {
                                label?: T;
                                href?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              pricingTable?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    subheading?: T;
                    tiers?:
                      | T
                      | {
                          name?: T;
                          price?: T;
                          period?: T;
                          description?: T;
                          features?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          cta?:
                            | T
                            | {
                                label?: T;
                                href?: T;
                              };
                          featured?: T;
                          badge?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              gallery?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    subheading?: T;
                    columns?: T;
                    images?:
                      | T
                      | {
                          image?: T;
                          caption?: T;
                          span?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              faq?:
                | T
                | {
                    variant?: T;
                    eyebrow?: T;
                    heading?: T;
                    subheading?: T;
                    image?: T;
                    items?:
                      | T
                      | {
                          question?: T;
                          answer?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              list?:
                | T
                | {
                    variant?: T;
                    eyebrow?: T;
                    heading?: T;
                    items?:
                      | T
                      | {
                          tag?: T;
                          title?: T;
                          text?: T;
                          href?: T;
                          tags?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              richText?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    columns?: T;
                    body?: T;
                    id?: T;
                    blockName?: T;
                  };
              video?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    subheading?: T;
                    poster?: T;
                    videoFile?: T;
                    videoUrl?: T;
                    features?:
                      | T
                      | {
                          icon?: T;
                          title?: T;
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              emailOptin?:
                | T
                | {
                    variant?: T;
                    eyebrow?: T;
                    heading?: T;
                    subheading?: T;
                    image?: T;
                    showNameField?: T;
                    submitLabel?: T;
                    formAction?: T;
                    disclaimer?: T;
                    id?: T;
                    blockName?: T;
                  };
              priceList?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    subheading?: T;
                    columns?: T;
                    items?:
                      | T
                      | {
                          image?: T;
                          name?: T;
                          description?: T;
                          price?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              timeline?:
                | T
                | {
                    variant?: T;
                    eyebrow?: T;
                    heading?: T;
                    subheading?: T;
                    items?:
                      | T
                      | {
                          date?: T;
                          icon?: T;
                          title?: T;
                          text?: T;
                          cta?:
                            | T
                            | {
                                label?: T;
                                href?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              social?:
                | T
                | {
                    variant?: T;
                    heading?: T;
                    text?: T;
                    links?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-entries_select".
 */
export interface TimeEntriesSelect<T extends boolean = true> {
  client?: T;
  site?: T;
  date?: T;
  minutes?: T;
  description?: T;
  billable?: T;
  invoiced?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}